name: JsonDoclet8

on:
  pull_request:
    paths:
      - "plugins/JsonDocletJava8/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "8.0"
          distribution: "adopt"
      - name: Test
        run: cd ./plugins/JsonDocletJava8 && ./gradlew testDoclet
